### ISSUE TITLE
Invalid path parameter

### ISSUE THREAD

**Issue by cloudguruab** [gangverk/getsling-api-docs#19]
- The following path is listed in docs as: https://api.getsling.com/#/timeclock/post_timeclock_clockin
- This path is for clocking in for shifts, but it is wrong.
- The valid path for proper documentation changes by the following:

```
Old Path: /timeclock/clockin
New path: /{org_id}/timeclock/clockin
```

**Comment by mrname** [comment]
> * The following path is listed in docs as: https://api.getsling.com/#/timeclock/post_timeclock_clockin
> * This path is for clocking in for shifts, but it is wrong.
> * The valid path for proper documentation changes by the following:
> 
> ```
> Old Path: /timeclock/clockin
> New path: /{org_id}/timeclock/clockin
> ```

Thanks for the issue! So actually, for almost all endpoints, I believe that org_id in the endpoint is optional. Is `/timeclock/clockin` not working for you without the org ID?

**Comment by cloudguruab** [comment]
Closing issue, no change needed!
